language: go

go:
  - 1.x
  - master

env:
  global:
    - GO111MODULE=true

matrix:
  allow_failures:
    - go: master

install:
  - make install

script:
  - make test-ci

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - MAKEFLAGS=" -j 2"
